no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
<<<<<<< HEAD
"Atomic" = 2
"Balance/Rebalance" = -8
"Code Improvement" = 2
"Mechanic" = -10
=======
"Administration" = 2
"Atomic" = 2
"Balance/Rebalance" = -8
"Code Improvement" = 2
"Content Expansion" = -3
>>>>>>> remotes/tg/master
"Feedback" = 2
"Fix" = 3
"Grammar and Formatting" = 1
"Hard Deletes" = 12
"Logging" = 1
<<<<<<< HEAD
=======
"Mechanic" = -10
>>>>>>> remotes/tg/master
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
"Quality of Life" = 1
<<<<<<< HEAD
"Content Expansion" = -3
=======
>>>>>>> remotes/tg/master
"Refactor" = 10
"Sound" = 3
"Sprites" = 3
"Unit Tests" = 6
