enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

<<<<<<< HEAD
=======
pnpEnableEsmLoader: false

>>>>>>> b396e73eb7a880ea83535400fc5abcb31f560b16
preferAggregateCacheInfo: true

preferInteractive: true

<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-3.0.1.cjs
=======
yarnPath: .yarn/releases/yarn-3.1.1.cjs
>>>>>>> b396e73eb7a880ea83535400fc5abcb31f560b16
